# Generated by Django 3.2.9 on 2021-12-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField(max_length=10)),
                ('image', models.ImageField(max_length=30, upload_to='')),
                ('release_date', models.DateField(max_length=30)),
                ('lte_exists', models.BooleanField(max_length=30)),
                ('slug', models.SlugField(max_length=30)),
            ],
        ),
    ]
